version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - RENUKE
  - Tera
  - okon
  - koff
  - ratemax
  - stephi
  - nkon
  - pgrst
  - ADSR
  - kcode
  - dacen
  - dacdata
  - logsinrom
  - exprom
  - SSGEG
import: []
