version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ADSR
  - dacdata
  - dacen
  - exprom
  - KEYONOFF
  - kcode
  - koff
  - LFOSEN
  - logsinrom
  - nkon
  - NTSC
  - okon
  - PAL
  - pgrst
  - ratemax
  - RENUKE
  - RNCM
  - samplecnt
  - SSGEG
  - stephi
  - Tera
import: []
