version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ADSR
  - chiptune
  - dacdata
  - dacen
  - exprom
  - GGIO
  - kcode
  - KEYONOFF
  - koff
  - LFOSEN
  - logsinrom
  - multipcm
  - nkon
  - NTSC
  - okim
  - okon
  - PAL
  - pgrst
  - qsound
  - ratemax
  - RENUKE
  - RNCM
  - samplecnt
  - SDLK
  - SSGEG
  - stephi
  - Tera
import: []
